server:
  port: 8099
data:
  mongodb:
    host: localhost
    port: 27017
    database: voters
logging:
  level:
    root: INFO
info:
  java:
    source: ${java.version}
    target: ${java.version}
---
spring:
  profiles: aws-production
data:
  mongodb:
    host: 10.0.1.6
logging:
  level:
    root: WARN
---
spring:
  profiles: docker-production
data:
  mongodb:
    host: mongodb
logging:
  level:
    root: WARN
